services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: mvpmatch
      POSTGRES_DB: mvpmatch
      POSTGRES_PASSWORD: mvpmatch
  mvpmatch:
    build: .
    environment:
      SECRET_KEY_BASE: so10KjHEFMfXQ9hcYuZyHYPO0RQRHLFY+CZWYW/dMWJRg7Jb4HIki/xR40YYNIq6 kiKouRTx7xViURdh0Z2d9A==
      DATABASE_URL: ecto://mvpmatch:mvpmatch@postgres/mvpmatch
      PHOENIX_JWT_KEY: 4yhobUhclygcJBFGC1QnH5DzQmHv05YeGDnFm2kC+6GcCY1VD4XUrCU0nQ6ROt3c
    ports:
      - "4000:4000"
    depends_on:
      - postgres
